### ISSUE TITLE
비로그인시 5시 30분 이전인데도 연장신청이 가능하다고 표시되는 오류.

### ISSUE THREAD

**Issue by Nooheat** [rlatjdfo112/DSM-Dormitory-System#164]
로그인 전 접속했을 때
5시 30분 이전임에도 불구하고 연장신청이 가능하다는 문구가 뜸.

로그인 시 정상적으로 불가능하다는 문구로 바뀜
![default](https://user-images.githubusercontent.com/26183416/29811857-d354c120-8cdf-11e7-837f-c2b268ee6ec9.png)

**Comment by AshtonYoon** [comment]
수정하게씁니다 ㅠㅠ 죄송합니다

**Comment by AshtonYoon** [comment]
수정완료했습니다 :)

**Comment by Nooheat** [comment]
`YOU ARE AWESOME`
