### ISSUE TITLE
DMS의 풀네임은 무엇인가요?

### ISSUE THREAD

**Issue by FuZer** [rlatjdfo112/DSM-Dormitory-System#6]
혹시 DSM의 오타인지 아니면 풀네임이 따로 있는건지 이해가 잘 안됩니다.

**Comment by graykick** [comment]
Dsm Management System입니다.

**Comment by FuZer** [comment]
Repo에 이름과 타이틀의 풀네임이 다른 이유는 무엇인가요?

**Comment by rlatjdfo112** [comment]
저희 팀원이 답변을 잘못해 드렸네요 Dormitory Management System 입니다.

**Comment by FuZer** [comment]
감사합니다.
